### ISSUE TITLE
PyPI release of 2.10

### ISSUE THREAD

**Issue by prsephton** [zopefoundation/grokproject#5]
@janwijbrand Can we push version 2.10 to PyPI please?  Current 2.9 on PyPI is broken :-)

**Comment by janwijbrand** [comment]
will do

**Comment by janwijbrand** [comment]
Done. Note the mistake in the CHANGES.txt. I had zest.releaser bump the version info for me. I did not realize you did that manually before. So version 2.10 is mentioned twice in the CHANGES.txt. Not a big problem for now. I'll clean up CHANGES.txt for subsequent releases.

**Comment by prsephton** [comment]
Thanks Jan, 

I'm sorry, but there is a problem introduced in 2.10;  The use of six.moves to import urllib introduced an incompatible read() result, leading to the Grok version number being escaped.  In short, using six.moves broke things.

Unfortunately it did not break the unit tests.  I have merged the fix.

**Comment by janwijbrand** [comment]
Can you update changes.txt too and then I can release 2.11

**Comment by prsephton** [comment]
Sure! will do that shortly.

**Comment by prsephton** [comment]
Merged changes.txt

**Comment by janwijbrand** [comment]
@prsephton you not need to update the version numbers and release dates in the CHANGES.txt yourself. That is done in the actual release process. What *is* important though is to keep the changelog up to date. I'm using zest.releaser that then will do all the necessary version bumps, release dates and tagging.

I'll release 2.11 and upload it to pypi.

**Comment by janwijbrand** [comment]
done.

**Comment by prsephton** [comment]
Thanks Jan!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
