### ISSUE TITLE
Error: Error downloading extends for URL http://svn.zope.org/*checkout*/zopetoolkit/tags/1.1.4/zopeapp.cfg:

### ISSUE THREAD

**Issue by mungayree** [zopefoundation/grokproject#6]
trying below on CentOS 7.4 with python 2.7.14.
pip install grok (installs nicely with all extentions)
pip install grokproject (install nicely)

while deploying the command of grokproject, 404 is observed via file in cfg -

log show -
        # paster create -t grok Sample
        ....

        Copying test_+project_lowercase+.py_tmpl to ./Sample/src/sample/tests/test_sample.py
        Copying tests.py_tmpl to ./Sample/src/sample/tests/tests.py

       Running /usr/local/bin/python /root/pkgs/Sample/bootstrap.py...
       Downloading http://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c11-py2.7.egg
       While:
                Initializing.
                Error: Error downloading extends for URL 
                http://svn.zope.org/*checkout*/zopetoolkit/tags/1.1.4/zopeapp.cfg:
                (404, 'Not Found')**
           Running /root/pkgs/Sample/bin/buildout -v...
           /bin/sh: /root/pkgs/Sample/bin/buildout: No such file or directory
           Running /usr/local/bin/python setup.py egg_info

**Comment by prsephton** [comment]
Thank you for your feedback.

We are in the process of fixing this; it should be working real soon.

Some time back all of the zopefoundation source was re-housed on github.  More recently the subversion (svn) servers were shot down.  Thus http://svn.zope.org/*checkout*/zopetoolkit/tags/1.1.4/zopeapp.cfg URL is invalid.  Grokproject used to refer to source housed by the svn servers, and such references now fail.

Kind regards

**Comment by prsephton** [comment]
@mungayree Hi;

The latest grokproject 2.11 has been released which fixes your problem (and a few others).

Note that you do not need to **pip install grok** in order to use grokproject, as grokproject installs a version of grok in the project it creates.

Let us know if you have further problems!
